"""Integration tests for Notification module endpoints."""
import uuid
from uuid import UUID

import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.notification.writer import write_notification


# ── Setup helpers ─────────────────────────────────────────────────────────────

async def _create_test_notification(
    client: AsyncClient, headers: dict, db_session: AsyncSession
) -> str:
    """Write a notification directly for the authenticated user.

    Returns the entity_id used, so tests can locate the notification.
    """
    me_resp = await client.get("/api/v1/users/me", headers=headers)
    assert me_resp.status_code == 200, me_resp.text
    me = me_resp.json()

    entity_id = uuid.uuid4()
    write_notification(
        db_session,
        org_id=UUID(me["organization_id"]),
        recipient_user_id=UUID(me["id"]),
        notification_type="TEST_NOTIFICATION",
        title="Test notification",
        body="Generated by integration test.",
        entity_type="test_entity",
        entity_id=entity_id,
    )
    await db_session.commit()
    return str(entity_id)


# ── Tests ─────────────────────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_notifications_initially_empty(client: AsyncClient, auth_headers: dict):
    """Initially GET /notifications/me returns an empty list (for this user's session)."""
    resp = await client.get("/api/v1/notifications/me", headers=auth_headers)
    assert resp.status_code == 200, resp.text
    # List could be non-empty from other tests; just validate shape
    assert isinstance(resp.json(), list)


@pytest.mark.asyncio
async def test_notification_count(client: AsyncClient, auth_headers: dict):
    """GET /notifications/me/count returns unread_count."""
    resp = await client.get("/api/v1/notifications/me/count", headers=auth_headers)
    assert resp.status_code == 200, resp.text
    data = resp.json()
    assert "unread_count" in data
    assert isinstance(data["unread_count"], int)


@pytest.mark.asyncio
async def test_notification_delivery(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """A written notification shows up in the recipient's feed and unread count."""
    count_before_resp = await client.get("/api/v1/notifications/me/count", headers=auth_headers)
    count_before = count_before_resp.json()["unread_count"]

    entity_id = await _create_test_notification(client, auth_headers, db_session)

    notif_resp = await client.get("/api/v1/notifications/me", headers=auth_headers)
    assert notif_resp.status_code == 200, notif_resp.text
    notifications = notif_resp.json()

    matching = [n for n in notifications if n["entity_id"] == entity_id]
    assert len(matching) == 1, f"Expected the test notification, got: {notifications}"

    count_after_resp = await client.get("/api/v1/notifications/me/count", headers=auth_headers)
    count_after = count_after_resp.json()["unread_count"]
    assert count_after > count_before


@pytest.mark.asyncio
async def test_mark_notification_read(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """POST /notifications/{id}/read marks notification as read."""
    entity_id = await _create_test_notification(client, auth_headers, db_session)

    notif_resp = await client.get("/api/v1/notifications/me", headers=auth_headers)
    assert notif_resp.status_code == 200, notif_resp.text
    notifications = notif_resp.json()
    matching = [
        n for n in notifications if n["entity_id"] == entity_id and not n["is_read"]
    ]
    assert len(matching) == 1, "Expected an unread test notification"
    notif_id = matching[0]["id"]

    read_resp = await client.post(
        f"/api/v1/notifications/{notif_id}/read",
        headers=auth_headers,
    )
    assert read_resp.status_code == 200, read_resp.text
    data = read_resp.json()
    assert data["is_read"] is True
    assert data["read_at"] is not None


@pytest.mark.asyncio
async def test_mark_all_notifications_read(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """POST /notifications/read-all marks all as read and returns updated count."""
    await _create_test_notification(client, auth_headers, db_session)

    resp = await client.post("/api/v1/notifications/read-all", headers=auth_headers)
    assert resp.status_code == 200, resp.text
    data = resp.json()
    assert "updated" in data
    assert isinstance(data["updated"], int)

    count_resp = await client.get("/api/v1/notifications/me/count", headers=auth_headers)
    assert count_resp.json()["unread_count"] == 0


@pytest.mark.asyncio
async def test_unread_only_filter(
    client: AsyncClient, auth_headers: dict, db_session: AsyncSession
):
    """GET /notifications/me?unread_only=true returns only unread notifications."""
    await _create_test_notification(client, auth_headers, db_session)

    resp = await client.get(
        "/api/v1/notifications/me",
        headers=auth_headers,
        params={"unread_only": "true"},
    )
    assert resp.status_code == 200, resp.text
    notifications = resp.json()
    assert isinstance(notifications, list)
    assert len(notifications) >= 1
    for n in notifications:
        assert n["is_read"] is False, f"Expected unread, got: {n}"
