"""
CQI (Continuous Quality Improvement) — attainment gap records.

Gaps are machine-generated by the attainment engine; they are never created by
hand. A CO gap is scoped to the section offering that failed to attain it (the
teacher who taught it can act on it). A PO gap is scoped to program + academic
term, aggregated across every offering that contributed to that PO, because no
single section owns a program outcome.

Implements BR-20: "When attainment is below threshold, the system MUST flag the
CO/PO for corrective action."
"""
import sqlalchemy as sa
from sqlalchemy import (
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID as PGUUID

from app.core.database import Base

# OPEN     — detected, nobody has committed to a fix yet
# ADDRESSED— an improvement action is attached and in progress (phase 2)
# CLOSED   — a later computation showed the outcome attained
# WAIVED   — a coordinator recorded a documented reason not to act
GAP_STATUSES = ("OPEN", "ADDRESSED", "CLOSED", "WAIVED")
_STATUS_CHECK = "status IN ('OPEN','ADDRESSED','CLOSED','WAIVED')"


class COAttainmentGap(Base):
    __tablename__ = "co_attainment_gaps"
    __table_args__ = (
        UniqueConstraint(
            "section_offering_id", "course_outcome_id",
            name="uq_cqi_co_gap_offering_co",
        ),
        CheckConstraint(_STATUS_CHECK, name="chk_cqi_co_gap_status"),
        Index("ix_cqi_co_gaps_org_status", "organization_id", "status"),
        {"schema": "cqi"},
    )

    id = Column(PGUUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()"))
    organization_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("org.organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    section_offering_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("curriculum.section_offerings.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    course_outcome_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("obe.course_outcomes.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Snapshot of the measurement that opened the gap, so the record stays
    # readable even after a recompute changes the live attainment row.
    #
    # attainment_pct is the share of students who scored at or above the CO
    # threshold — the figure the engine actually compares against threshold_pct.
    # average_score_pct is the mean CO score, kept for context: a cohort can
    # average well and still fail the gate if the marks are lopsided.
    attainment_pct = Column(Numeric(5, 2), nullable=False)
    average_score_pct = Column(Numeric(5, 2), nullable=False)
    threshold_pct = Column(Numeric(5, 2), nullable=False)
    students_above_threshold = Column(Integer, nullable=False)
    total_students = Column(Integer, nullable=False)
    status = Column(String(20), nullable=False, server_default=sa.text("'OPEN'"))
    detected_at = Column(DateTime(timezone=True), nullable=False, server_default=sa.text("now()"))
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    # user_id stored without ORM FK — avoids cross-schema model coupling with IAM
    waived_by_user_id = Column(PGUUID(as_uuid=True), nullable=True)
    waiver_reason = Column(Text, nullable=True)
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
        onupdate=sa.text("now()"),
    )


class POAttainmentGap(Base):
    __tablename__ = "po_attainment_gaps"
    __table_args__ = (
        UniqueConstraint(
            "program_id", "academic_term_id", "program_outcome_id",
            name="uq_cqi_po_gap_program_term_po",
        ),
        CheckConstraint(_STATUS_CHECK, name="chk_cqi_po_gap_status"),
        Index("ix_cqi_po_gaps_org_status", "organization_id", "status"),
        {"schema": "cqi"},
    )

    id = Column(PGUUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()"))
    organization_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("org.organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    program_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("org.programs.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    academic_term_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("curriculum.academic_terms.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    program_outcome_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("obe.program_outcomes.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Mean of per-offering PO attainment across the program for this term.
    aggregate_attainment_pct = Column(Numeric(5, 2), nullable=False)
    threshold_pct = Column(Numeric(5, 2), nullable=False)
    contributing_offering_count = Column(Integer, nullable=False)
    attained_offering_count = Column(Integer, nullable=False)
    status = Column(String(20), nullable=False, server_default=sa.text("'OPEN'"))
    detected_at = Column(DateTime(timezone=True), nullable=False, server_default=sa.text("now()"))
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    # user_id stored without ORM FK — avoids cross-schema model coupling with IAM
    waived_by_user_id = Column(PGUUID(as_uuid=True), nullable=True)
    waiver_reason = Column(Text, nullable=True)
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sa.text("now()"),
        onupdate=sa.text("now()"),
    )
